--- 
language: php

php:
  - 5.3
  - 5.4
  - 5.5

#whitelist
branches:
  only:
    - master
    - /^feature-.*$/

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - composer install --dev

after_script:
  php vendor/bin/coveralls -v