--- 
language: php

php:
  - 5.3
  - 5.4
  - 5.5

#whitelist
branches:
  only:
    - master
    - /^feature-.*$/

script: phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - composer require --dev satooshi/php-coveralls:0.6.*

after_script: php vendor/bin/coveralls -v